channels:
- defaults
dependencies:
- python=3.10.12
- pip<=23.1.2
- pip:
  - mlflow
  - cloudpickle==2.2.1
  - numpy==1.23.5
  - pathlib==1.0.1
  - pyyaml==6.0.1
  - scikit-learn==1.2.2
  - scipy==1.11.3
name: mlflow-project-env